provider:
    name: openfaas
    gateway: mygateway.com

functions:
    api-registration:
        lang: dockerfile
        handler: ./
        image: gcr.io/amapogotagview/user-registration:latest
        environment:
            REDIS_HOST: redis://openfaas-fn-redis-master

            TWILIO_ACCOUNT_SSID:
            TWILIO_AUTH_TOKEN:
            TWILIO_NUMBER_FROM:

            SMS_PORTAL_CLIENT_ID:
            SMS_PORTAL_SECRET:

            KC_BASE:
            KC_REALM:
            KC_CLIENT_SECRET:
            KC_CLIENT_ID:
